services: 
    db-postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: trading_journal
      ports:
        - "5432:5432"
    pgadmin:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
        PGADMIN_DEFAULT_PASSWORD: strong-password
      ports:
        - "8888:80"